spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
      keyspace-name: redis
  jpa:
    hibernate:
      ddl-auto: update

server:
  shutdown: graceful